---
- name: create composer config directory
  file:
    name=~/.composer
    mode=0755
    state=directory

- name: generate composer config
  template:
    src=config.json.j2
    dest=~/.composer/config.json
    mode=0600

- name: download composer installer
  get_url: url=https://getcomposer.org/installer
    dest=/tmp/composer-installer.php
    mode=0755

- name: run composer installer
  command: /usr/bin/php composer-installer.php
    chdir=/tmp
    creates=/tmp/composer.phar

- name: copy composer in place
  sudo: true
  command: /bin/cp /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
